import type { Metadata } from 'next';
import { DM_Sans, Geist, Inter } from 'next/font/google';
import './globals.css';

import './globals.css';
import { cn } from '@/lib/utils';
import { Toaster } from 'sonner';
import Script from 'next/script';
import { TooltipProvider } from '@/components/ui/tooltip';

const dmSans = DM_Sans({
  subsets: ['latin'],
  variable: '--font-dm-sans',
  fallback: ['sans-serif'],
});

const sansSarif = Inter({
  variable: '--font-sans-sarif',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="lazyOnload"
        />
      </head>
      <body
        className={cn(
          `${dmSans.variable} ${sansSarif.variable} relative`,
          'overflow-x-hidden',
        )}
      >
        <TooltipProvider>{children}</TooltipProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
